server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 100
      min-spare: 30
  port: 8080
  servlet:
    context-path: /
    session:
      cookie:
        http-only: true


spring:
  application:
    name: be-water-market
  profiles:
    default: dev
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

springdoc:
  api-docs:
    path: v3/api-docs



logging:
  level:
    root: info
    com.github: info



easy-trans:

  is-enable-redis: false

  is-enable-global: true

  is-enable-tile: true


mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml

  typeAliasesPackage: com.github.*.entity
  global-config:

    db-config:

      id-type: AUTO

      logic-delete-value: 1

      logic-not-delete-value: 0
    banner: false

  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
  configuration-properties:
    prefix:
    blobType: BLOB
    boolValue: TRUE
